dataloader:
  ros__parameters:
    data_path: /home/abhiyaan-cu/ardc_ws/src/LiDAR-Processing-V2/data
    vis_cloud_topic: /pointcloud_unorganized
    organized_cloud_topic: /pointcloud_organized
    frequency_hz: 10
