# This file consolidates all parameters for the urban_road_filter package.
urban_road_filter:
  ros__parameters:
    fixed_frame: "/livox"  # Fixed frame. (Restart needed if it changes.)
    topic_name: "/livox_PointCloud2"  # The desired topic to subscribe to.

    # Enabling individual detection methods.
    x_zero_method: true  # x zero method.
    z_zero_method: true  # z zero method.
    star_shaped_method: true  # star shaped method.
    blind_spots: true  # Filtering blind spots.

    # Blindspot detection (x-direction)
    xDirection: true  # Added xDirection parameter with a valid boolean value.

    # LIDAR's vertical resolution
    interval: 0.157  #was 0.18

    # Estimated minimum height of the curb (in meters).
    curb_height: 0.01

    # Estimated number of points on the curb.
    curb_points: 2

    # Width of the beam zone (in degrees).
    beamZone: 30


    min_x: -30.0
    max_x: 30.0
    min_y: -30.0
    max_y: 30.0
    min_z: -2.0
    max_z: 1.0


    cylinder_deg_x: 110.0
    cylinder_deg_z: 100.0
    curb_slope_deg: 35.0

    dmin_param: 4
    kdev_param: 1.5
    kdist_param: 2.0


    # Star-beam Filter
    starbeam_filter: true  # Use rectangular beams for detection instead of the whole sectors (StarShaped). Was false

    # Polygon simplification settings (CSP).
    simple_poly_allow: false  # Use simplified polygon (height data will be lost). Was true
    poly_s_param: 0.7  # Coefficient of polygon simplification.
    poly_z_manual: -1.5  # Set a constant polygon height.
    poly_z_avg_allow: true  # Set polygon height to average value.