<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="igvc_robot">

  <!-- ============================= -->
  <!-- Robot Properties -->
  <!-- ============================= -->
  <xacro:property name="base_length" value="0.936718"/>
  <xacro:property name="base_width" value="0.7"/>
  <xacro:property name="base_height" value="0.275"/>

  <xacro:property name="wheel_radius" value="0.1524"/>
  <xacro:property name="wheel_width" value="0.1"/>
  <xacro:property name="wheel_y_offset" value="0.411"/>
  <xacro:property name="wheel_x_offset" value="0.3"/>
  <xacro:property name="mass_base" value="1.0"/>
  <xacro:property name="mass_wheel" value="0.5"/>
  <xacro:property name="connecting_rod_length" value="0.1715"/>
  <xacro:property name="connecting_rod_radius" value="0.0233"/>
  <xacro:property name="connecting_rod_x_offset" value="-0.418"/>
  <xacro:property name="castor_wheel_radius" value="0.035"/>
  <xacro:property name="castor_wheel_width" value="0.01867"/>

  <xacro:property name="M_PI" value="3.1415926535897931"/>

  <!-- ============================= -->
  <!-- MATERIALS (for RViz) -->
  <!-- ============================= -->
  <material name="metal_gray"><color rgba="0.6 0.6 0.6 1.0"/></material>
  <material name="black_rubber"><color rgba="0.1 0.1 0.1 1.0"/></material>
  <material name="aluminum_silver"><color rgba="0.8 0.8 0.85 1.0"/></material>
  <material name="blue_highlight"><color rgba="0.0 0.3 0.8 1.0"/></material>

 

  <!-- ============================= -->
  <!-- Base Link -->
  <!-- ============================= -->
  <link name="base_link">
    <visual>
      <geometry><box size="${base_length} ${base_width} ${base_height}"/></geometry>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <material name="metal_gray"/>
    </visual>
    <collision>
      <geometry><box size="${base_length} ${base_width} ${base_height}"/></geometry>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="${mass_base}"/>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
      <inertia ixx="0.083" iyy="0.083" izz="0.083" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <gazebo reference="base_link">
    <material>Gazebo/Gray</material>
  </gazebo>

  <!-- ============================= -->
  <!-- Left Wheel -->
  <!-- ============================= -->
  <link name="left_wheel">
    <visual>
      <geometry><cylinder length="${wheel_width}" radius="${wheel_radius}"/></geometry>
      <origin xyz="0 0 0" rpy="0 1.5708 0"/>
      <material name="black_rubber"/>
    </visual>
    <collision>
      <geometry><cylinder length="${wheel_width}" radius="${wheel_radius}"/></geometry>
      <origin xyz="0 0 0" rpy="0 1.5708 0"/>
    </collision>
    <inertial>
      <mass value="${mass_wheel}"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.006" iyy="0.006" izz="0.001" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <origin xyz="${wheel_x_offset} ${wheel_y_offset} 0" rpy="0 0 1.57"/>
    <axis xyz="0 1 0"/>
  </joint>

  <gazebo reference="left_wheel">
    <material>Gazebo/Black</material>
  </gazebo>

  <!-- ============================= -->
  <!-- Right Wheel -->
  <!-- ============================= -->
  <link name="right_wheel">
    <visual>
      <geometry><cylinder length="${wheel_width}" radius="${wheel_radius}"/></geometry>
      <origin xyz="0 0 0" rpy="0 1.5708 0"/>
      <material name="black_rubber"/>
    </visual>
    <collision>
      <geometry><cylinder length="${wheel_width}" radius="${wheel_radius}"/></geometry>
      <origin xyz="0 0 0" rpy="0 1.5708 0"/>
    </collision>
    <inertial>
      <mass value="${mass_wheel}"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.006" iyy="0.006" izz="0.001" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin xyz="${wheel_x_offset} -${wheel_y_offset} 0" rpy="0 0 1.57"/>
    <axis xyz="0 1 0"/>
  </joint>

  <gazebo reference="right_wheel">
    <material>Gazebo/Black</material>
  </gazebo>

  <!-- ============================= -->
  <!-- Connecting Rod -->
  <!-- ============================= -->
  <link name="connecting_rod">
    <visual>
      <geometry><cylinder length="${connecting_rod_length}" radius="${connecting_rod_radius}"/></geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="aluminum_silver"/>
    </visual>
    <collision>
      <geometry><cylinder length="${connecting_rod_length}" radius="${connecting_rod_radius}"/></geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.2"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.002" iyy="0.002" izz="0.001" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="connecting_rod_joint" type="continuous">
    <parent link="base_link"/>
    <child link="connecting_rod"/>
    <origin xyz="${connecting_rod_x_offset} 0 -${connecting_rod_length/2-0.05}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <gazebo reference="connecting_rod">
    <material>Gazebo/Silver</material>
  </gazebo>

  <!-- ============================= -->
  <!-- Castor Wheel -->
  <!-- ============================= -->
  <link name="castor_wheel">
    <visual>
      <geometry><cylinder length="${castor_wheel_width}" radius="${castor_wheel_radius}"/></geometry>
      <origin xyz="0 0 0" rpy="0 1.5708 0"/>
      <material name="black_rubber"/>
    </visual>
    <collision>
      <geometry><cylinder length="${castor_wheel_width}" radius="${castor_wheel_radius}"/></geometry>
      <origin xyz="0 0 0" rpy="0 1.5708 0"/>
    </collision>
    <inertial>
      <mass value="0.2"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.006" iyy="0.006" izz="0.001" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="castor_wheel_joint" type="continuous">
    <parent link="connecting_rod"/>
    <child link="castor_wheel"/>
    <origin xyz="0 0 -${connecting_rod_length/2}" rpy="0 0 1.57"/>
    <axis xyz="0 1 0"/>
  </joint>

  <gazebo reference="castor_wheel">
    <material>Gazebo/Black</material>
  </gazebo>

  <!-- ============================= -->
  <!-- Base Footprint -->
  <!-- ============================= -->
  
  <link name="base_footprint"/>
  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>


  <!-- ============================= -->
  <!-- Differential Drive -->
  <!-- ============================= -->

  <gazebo>
  <plugin name='diff_drive' filename='libgazebo_ros_diff_drive.so'>
    <ros>
      <namespace>/</namespace>
    </ros>

    <!-- wheels -->
    <left_joint>left_wheel_joint</left_joint>
    <right_joint>right_wheel_joint</right_joint>

    <!-- kinematics -->
    <wheel_separation>${2*wheel_y_offset}</wheel_separation>
    <wheel_diameter>${2*wheel_radius}</wheel_diameter>

    <!-- limits -->
    <max_wheel_torque>20</max_wheel_torque>
    <max_wheel_acceleration>1.0</max_wheel_acceleration>

    <!-- output -->
    <publish_odom>true</publish_odom>
    <publish_odom_tf>true</publish_odom_tf>
    <publish_wheel_tf>true</publish_wheel_tf>

    <odometry_frame>odom</odometry_frame>
    <robot_base_frame>base_link</robot_base_frame>
  </plugin>
  </gazebo>

</robot>
